project:
  type: website
  output-dir: docs

website:
  title: "Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: methods.qmd
        text: Methods
      - href: musings.qmd
        text: Musings
      - href: presentations.qmd
        text: Presentations
      - about.qmd
      - href: connect.qmd
        text: Connect

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

