---
title: "Inferring Markov Chains"
author: "BPR"
---

A while ago I had a problem that would likely be addressed if I could model the data with a *kth*-order Markov chain. Before jumping in, I looked to see what anyone else had done, and as often seems to be the case when I find a problem that I'm interested in, I found [a paper](https://link.aps.org/doi/10.1103/PhysRevE.76.011106) with James Crutchfield as the second author that has a lot to say on the topic. (I've never met him, but Crutchfield seems to have rather nice insights into a wide range of problems.) The paper starts off "Statistical inference of models from small data samples is a vital tool in the understanding of natural systems. In many problems of interest data consists of a sequence of letters from a finite *alphabet*." (Emphasis in the original.) This sounds just the thing for working with ecological momentary assessment (EMA) data.

An aside: EMA data generally consists of a number of survey questions (usually individual questions taken from psychological scales, like questions about depression taken from the PHQ-9,) answered on a cell phone app one or more times per day for a number of days. For example, data collected by Heather Littleton and colleagues asked hurricane survivors about 25 questions every day for 6 weeks. These questions can be used to create psychological "states" for each round of data collection, either by looking at the full scales from which the data are collected, or by clustering the responses, or some other method. This results in a "finite alphabet" of states, which are great fodder for Markov chains.

The problem, then, is to use the data to infer the appropriate order of Markov chain and to estimate the entries in the matrix, hopefully including confidence intervals (or in this case, Bayesian *posterior credible intervals*,) on those estimates. It is at this point that the paper of Strelioff et al. (2007) comes into play. The authors use a Bayesian approach to determine both the order and entries of the Markov matrices. However, like many papers, the whole thing needs some unpacking to be easily moved beyond the demonstrations in the paper. So, I sat down to do just that.
